version: '2'
networks:
  ftgo: {}
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - ftgo
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    networks:
      - ftgo
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
    networks:
      - ftgo
  service-discovery:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-discovery
    ports:
      - "8761:8761"
    networks:
      - ftgo

  api-gateway:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-apigateway
    environment:
      - EUREKA_URL=service-discovery:8761
    ports:
      - "8000:8000"
    networks:
      - ftgo

  order:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-order
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - KAFKA_URL=kafka:29092
      - EUREKA_URL=service-discovery:8761
    networks:
      - ftgo

  kitchen:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-kitchen
    environment:
        - MONGO_HOST=mongo
        - MONGO_PORT=27017
        - EUREKA_URL=service-discovery:8761
    networks:
        - ftgo

  payment:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-payment
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - KAFKA_URL=kafka:29092
    networks:
      - ftgo


