server:
  port: 8000
spring:
  application:
    name: api-gateway
  security:
    user:
      name: guilherme
      password: microservices
  cloud:
    gateway:
      routes:
        - id: order-ms
          uri: lb://order-ms
          predicates:
            - Path=/orders/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost:8761}/eureka
  instance:
    preferIpAddress: true


basic-auth: Z3VpbGhlcm1lOm1pY3Jvc2VydmljZXM=
