apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  containers:
   - name: api-gateway
     image: guilhermebehs/api-gateway:1.0.0
     ports:
      - containerPort: 8000
     env:
      - name: EUREKA_URL
        value: service-discovery-svc:8761
          
