apiVersion: v1
kind: Pod
metadata:
  name: kitchen
  labels:
    app: kitchen
spec:
  containers:
   - name: kitchen
     image: guilhermebehs/kitchen:1.0.0
     ports:
      - containerPort: 8760
     env:
      - name: MONGO_HOST
        value: "mongo-svc"
      - name: MONGO_PORT
        value: "27017"
      - name: KAFKA_URL
        value: kafka-svc:29092
      - name: EUREKA_URL
        value: service-discovery-svc:8761
          
