apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: mongo
      name: mongo  
    spec:
      containers:
        - name: mongo
          image: mongo:3
          ports:
            - containerPort: 27017
          volumeMounts:
                - name: data
                  mountPath: /data/db
                
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc             
  selector: 
     matchLabels:
        app: mongo
  serviceName: mongo-svc 