apiVersion: v1
kind: Pod
metadata:
  name: order
  labels:
    app: order
spec:
  containers:
   - name: order
     image: guilhermebehs/order:1.0.0
     ports:
      - containerPort: 8763
     env:
      - name: MONGO_HOST
        value: "mongo-svc"
      - name: MONGO_PORT
        value: "27017"
      - name: KAFKA_URL
        value: kafka-svc:29092
      - name: EUREKA_URL
        value: service-discovery-svc:8761
          
