apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    app: payment
spec:
  containers:
   - name: payment
     image: guilhermebehs/payment:1.0.0
     ports:
      - containerPort: 29092
     env:
      - name: MONGO_HOST
        value: "mongo-svc"
      - name: MONGO_PORT
        value: "27017"
      - name: KAFKA_URL
        value: kafka-svc:29092