apiVersion: v1
kind: Pod
metadata:
  name: service-discovery
  labels:
    app: service-discovery
spec:
  containers:
   - name: service-discovery
     image: guilhermebehs/service-discovery:1.0.0
     ports:
      - containerPort: 8761