apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template: 
    metadata: 
      name: zookeeper
      labels:
        app: zookeeper
    spec:    
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        ports:
          - containerPort: 2181
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"    
        resources:
              requests:
                cpu: 300m
              limits:
                cpu: 350m
  selector:
    matchLabels:
        app: zookeeper          

    