FROM maven:3.6.0-jdk-11-slim AS build


WORKDIR /home/app

COPY . /home/app/

RUN mvn clean package -pl apigateway


FROM openjdk:11-jre-slim

WORKDIR /home/app

COPY --from=build /home/app/apigateway/target/apigateway-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8000

ENTRYPOINT ["java","-jar","app.jar"]