FROM maven:3.6.0-jdk-11-slim AS build


WORKDIR /home/app

COPY . /home/app/

RUN mvn clean package -pl kitchen


FROM openjdk:11-jre-slim

WORKDIR /home/app

COPY --from=build /home/app/kitchen/target/kitchen-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java","-jar","app.jar"]