FROM maven:3.6.0-jdk-11-slim AS build


WORKDIR /home/app

COPY . /home/app/

RUN mvn clean package -pl payment


FROM openjdk:11-jre-slim

WORKDIR /home/app

COPY --from=build /home/app/payment/target/payment-0.0.1-SNAPSHOT.jar app.jar


ENTRYPOINT ["java","-jar","app.jar"]