server:
  port: ${PORT:8761}
eureka:
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus