spring:
  application:
    name: kitchen-ms
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: kitchen-ms
      auto-index-creation: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost:8761}/eureka
  instance:
    preferIpAddress: true
    hostname: kitchen-ms
server:
  port: ${PORT:8081}