spring:
  application:
    name: kitchen-ms
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kitchen-ms
      auto-index-creation: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: kitchen-ms
server:
  port: 8081